// Awareness days & important dates for NSS activity ideas (March–December)

export interface CalendarEvent {
  name: string;
  date: string; // MM-DD
  activity: string;
}

export const calendarEvents: CalendarEvent[] = [
  // === MARCH ===
  { name: "Zero Discrimination Day", date: "03-01", activity: "Awareness rally on equality, poster-making, pledge campaigns." },
  { name: "World Civil Defence Day", date: "03-01", activity: "Fire safety drills, first aid training, emergency preparedness workshop." },
  { name: "Ramakrishna Jayanti", date: "03-02", activity: "Talk on Swami Vivekananda's ideals, youth motivation session." },
  { name: "World Compliment Day", date: "03-01", activity: "Gratitude wall, appreciation cards for staff and peers." },
  { name: "World Wildlife Day", date: "03-03", activity: "Wildlife photo exhibition, tree plantation, documentary screening." },
  { name: "World Hearing Day", date: "03-03", activity: "Free hearing check camp, sign language awareness session." },
  { name: "National Safety Day", date: "03-04", activity: "Road safety campaign, fire safety demo, helmet awareness drive." },
  { name: "National Grammar Day", date: "03-04", activity: "Language quiz, essay competition on social issues." },
  { name: "International Women's Day", date: "03-08", activity: "Awareness program, campus rally, women's health camp, self-defence workshop." },
  { name: "Mauritius Day", date: "03-12", activity: "Cultural exchange event, diversity celebration." },
  { name: "No Smoking Day", date: "03-13", activity: "Anti-tobacco rally, poster competition, health pledge campaign." },
  { name: "Holika Dahan", date: "03-13", activity: "Eco-friendly celebration, community bonfire, cultural program." },
  { name: "Holi", date: "03-14", activity: "Organic color Holi, water conservation awareness, community celebration." },
  { name: "Pi Day", date: "03-14", activity: "Math quiz, STEM awareness event for school children." },
  { name: "International Day of Action for Rivers", date: "03-14", activity: "River cleanup drive, water pollution awareness walk." },
  { name: "World Consumer Rights Day", date: "03-15", activity: "Consumer rights awareness stall, skit on digital fraud." },
  { name: "World Sleep Day", date: "03-15", activity: "Mental health workshop, stress management session." },
  { name: "National Vaccination Day", date: "03-16", activity: "Vaccination awareness campaign, health camp coordination." },
  { name: "Ordnance Factories Day", date: "03-18", activity: "Defence awareness talk, patriotic event." },
  { name: "Nowruz", date: "03-20", activity: "Cultural diversity celebration, international food stall." },
  { name: "International Day of Happiness", date: "03-20", activity: "Happiness pledge, community fun activities, visit to old age home." },
  { name: "World Sparrow Day", date: "03-20", activity: "Bird feeder making, sparrow conservation awareness." },
  { name: "World Oral Health Day", date: "03-20", activity: "Free dental check-up camp, oral hygiene awareness drive." },
  { name: "World Forestry Day", date: "03-21", activity: "Tree plantation drive, forest conservation rally." },
  { name: "World Down Syndrome Day", date: "03-21", activity: "Inclusive activities, awareness session on disability rights." },
  { name: "World Poetry Day", date: "03-21", activity: "Poetry recitation on social themes, open mic event." },
  { name: "Bihar Diwas", date: "03-22", activity: "Cultural showcase, heritage awareness." },
  { name: "World Water Day", date: "03-22", activity: "Water conservation rally, rainwater harvesting demo, clean water campaign." },
  { name: "World Meteorological Day", date: "03-23", activity: "Climate change awareness, weather monitoring workshop." },
  { name: "Martyr's Day", date: "03-23", activity: "Tribute to freedom fighters, patriotic rally, NCC-NSS joint event." },
  { name: "World Tuberculosis Day", date: "03-24", activity: "TB awareness camp, free screening coordination, poster campaign." },
  { name: "International Day of the Unborn Child", date: "03-25", activity: "Maternal health awareness, prenatal care information drive." },
  { name: "Purple Day of Epilepsy", date: "03-26", activity: "Epilepsy awareness session, wear purple campaign." },
  { name: "World Theatre Day", date: "03-27", activity: "Street play on social issues, drama competition." },
  { name: "World Piano Day", date: "03-28", activity: "Musical event, cultural evening for community." },
  { name: "Rajasthan Day", date: "03-30", activity: "Cultural heritage event, folk art exhibition." },
  { name: "Eiffel Tower Day", date: "03-31", activity: "Engineering marvel quiz, STEM awareness event." },
  { name: "Ramadan (begins)", date: "03-12", activity: "Interfaith harmony event, community iftar, food donation drive." },
  { name: "Eid (end of Ramadan)", date: "03-31", activity: "Community celebration, charity drive, inclusive feast." },

  // === APRIL ===
  { name: "World Autism Awareness Day", date: "04-02", activity: "Inclusive event, autism awareness walk, blue light campaign." },
  { name: "International Fact-Checking Day", date: "04-02", activity: "Media literacy workshop, fake news awareness session." },
  { name: "International Day of Mine Awareness", date: "04-04", activity: "Safety awareness talk, documentary screening." },
  { name: "International Carrot Day", date: "04-04", activity: "Nutrition awareness, healthy eating workshop." },
  { name: "National Maritime Day", date: "04-05", activity: "Maritime heritage awareness, ocean conservation talk." },
  { name: "International Day of Conscience", date: "04-05", activity: "Peace pledge, value-based discussion forum." },
  { name: "International Day of Sport for Development and Peace", date: "04-06", activity: "Sports day for underprivileged children, peace through sports event." },
  { name: "Rama Navami", date: "04-06", activity: "Cultural program, community service, temple cleaning drive." },
  { name: "World Health Day", date: "04-07", activity: "Free health check-up camp, health awareness rally, yoga session." },
  { name: "World Homoeopathy Day", date: "04-10", activity: "Alternative medicine awareness, health talk." },
  { name: "Siblings Day", date: "04-10", activity: "Family bonding event, community togetherness program." },
  { name: "Mahavir Jayanti", date: "04-10", activity: "Non-violence awareness walk, Ahimsa pledge campaign." },
  { name: "National Safe Motherhood Day", date: "04-11", activity: "Maternal health camp, women's wellness drive." },
  { name: "World Parkinson's Day", date: "04-11", activity: "Senior citizen care visit, awareness session." },
  { name: "Hanuman Jayanti", date: "04-12", activity: "Community service, strength & discipline workshop." },
  { name: "Jallianwala Bagh Massacre Remembrance Day", date: "04-13", activity: "Patriotic event, history talk, tribute to martyrs." },
  { name: "Baisakhi", date: "04-13", activity: "Harvest celebration, cultural program, community feast." },
  { name: "B.R. Ambedkar Remembrance Day", date: "04-14", activity: "Constitution awareness rally, social justice seminar." },
  { name: "Puthandu", date: "04-14", activity: "Tamil New Year cultural celebration." },
  { name: "Solar New Year", date: "04-14", activity: "Cultural diversity celebration, traditional games." },
  { name: "Vishu", date: "04-14", activity: "Kerala cultural event, community gathering." },
  { name: "Pohela Boishakh", date: "04-14", activity: "Bengali New Year celebration, cultural showcase." },
  { name: "World Haemophilia Day", date: "04-17", activity: "Blood disorder awareness, blood donation camp." },
  { name: "World Heritage Day", date: "04-18", activity: "Heritage walk, monument cleaning, cultural preservation rally." },
  { name: "Good Friday", date: "04-18", activity: "Interfaith harmony, community service, charity work." },
  { name: "World Liver Day", date: "04-19", activity: "Liver health awareness camp, anti-alcohol campaign." },
  { name: "Easter Sunday", date: "04-20", activity: "Community celebration, egg painting for children, charity event." },
  { name: "National Civil Service Day", date: "04-21", activity: "Public service appreciation event, governance awareness talk." },
  { name: "World Earth Day", date: "04-22", activity: "Campus cleanup, tree plantation, e-waste collection drive, eco pledge." },
  { name: "World Book and Copyright Day", date: "04-23", activity: "Book donation drive, reading marathon, library visit." },
  { name: "English Language Day", date: "04-23", activity: "Language skills workshop, debate competition." },
  { name: "National Panchayati Raj Day", date: "04-24", activity: "Local governance awareness, village visit, civic duty talk." },
  { name: "World Day for Animals in Laboratories", date: "04-24", activity: "Animal welfare awareness, cruelty-free pledge." },
  { name: "World Malaria Day", date: "04-25", activity: "Mosquito net distribution, malaria prevention awareness rally." },
  { name: "World Penguin Day", date: "04-25", activity: "Climate change impact awareness, wildlife conservation talk." },
  { name: "World Intellectual Property Day", date: "04-26", activity: "IPR awareness workshop, innovation quiz." },
  { name: "World Tapir Day", date: "04-27", activity: "Endangered species awareness, wildlife poster exhibition." },
  { name: "World Design Day", date: "04-27", activity: "Design thinking workshop, community problem-solving session." },
  { name: "World Day for Safety and Health at Work", date: "04-28", activity: "Workplace safety demo, first-aid training camp." },
  { name: "International Dance Day", date: "04-29", activity: "Flash mob for social cause, cultural dance event." },
  { name: "International Astronomy Day", date: "04-29", activity: "Stargazing event, space science quiz for school students." },
  { name: "International Sculpture Day", date: "04-29", activity: "Art workshop, sculpture from recycled materials." },
  { name: "World Veterinary Day", date: "04-26", activity: "Animal health camp, stray animal care drive." },
  { name: "International Jazz Day", date: "04-30", activity: "Music for peace event, cultural evening." },
  { name: "Ayushman Bharat Diwas", date: "04-30", activity: "Health scheme awareness, free health check-up camp." },

  // === MAY ===
  { name: "International Labour Day", date: "05-01", activity: "Workers' rights awareness, felicitate campus staff, labour welfare drive." },
  { name: "Maharashtra Day", date: "05-01", activity: "Cultural celebration, Marathi heritage event." },
  { name: "Gujarat Day", date: "05-01", activity: "Gujarati cultural showcase, community celebration." },
  { name: "World Tuna Day", date: "05-02", activity: "Marine conservation awareness, sustainable fishing talk." },
  { name: "World Press Freedom Day", date: "05-03", activity: "Media literacy workshop, journalism ethics discussion." },
  { name: "Coal Miners Day", date: "05-04", activity: "Mining safety awareness, energy conservation talk." },
  { name: "International Firefighter's Day", date: "05-04", activity: "Fire safety training, felicitate local firefighters." },
  { name: "World Laughter Day", date: "05-04", activity: "Laughter yoga session, visit children's home with fun activities." },
  { name: "International No Diet Day", date: "05-06", activity: "Body positivity awareness, nutrition talk." },
  { name: "World Asthma Day", date: "05-06", activity: "Respiratory health camp, air pollution awareness rally." },
  { name: "World Athletics Day", date: "05-07", activity: "Sports event for underprivileged youth, fitness awareness run." },
  { name: "World Red Cross Day", date: "05-08", activity: "Blood donation camp, first-aid training, Red Cross volunteer signup." },
  { name: "World Thalassaemia Day", date: "05-08", activity: "Blood disorder awareness, screening camp coordination." },
  { name: "Rabindranath Tagore Jayanti", date: "05-09", activity: "Poetry recitation, cultural program, literary quiz." },
  { name: "Maharana Pratap Jayanti", date: "05-09", activity: "Bravery & patriotism talk, historical quiz." },
  { name: "World Lupus Day", date: "05-10", activity: "Autoimmune disease awareness session." },
  { name: "National Technology Day", date: "05-11", activity: "Tech exhibition, innovation hackathon, STEM workshop." },
  { name: "Mother's Day", date: "05-11", activity: "Visit old age home, felicitate mothers, gratitude campaign." },
  { name: "International Nurses Day", date: "05-12", activity: "Felicitate nurses at local hospital, healthcare appreciation event." },
  { name: "Buddha Jayanti", date: "05-12", activity: "Peace walk, meditation session, non-violence awareness." },
  { name: "International Day of Families", date: "05-15", activity: "Family health awareness camp, community bonding event." },
  { name: "National Dengue Day", date: "05-16", activity: "Anti-dengue drive, campus cleanliness, awareness posters." },
  { name: "International Day of Light", date: "05-16", activity: "Solar energy awareness, LED distribution in villages." },
  { name: "National Endangered Species Day", date: "05-16", activity: "Wildlife conservation rally, poster making." },
  { name: "World Telecommunication Day", date: "05-17", activity: "Digital literacy workshop, internet safety awareness." },
  { name: "World Hypertension Day", date: "05-17", activity: "Blood pressure check-up camp, heart health talk." },
  { name: "Armed Forces Day", date: "05-17", activity: "Tribute to armed forces, patriotic rally." },
  { name: "World AIDS Vaccine Day", date: "05-18", activity: "HIV/AIDS awareness campaign, safe health practices talk." },
  { name: "International Museum Day", date: "05-18", activity: "Museum visit, heritage preservation awareness." },
  { name: "International HR Day", date: "05-20", activity: "Career guidance session, workplace culture talk." },
  { name: "National Anti-Terrorism Day", date: "05-21", activity: "Peace pledge, anti-terrorism awareness rally." },
  { name: "International Tea Day", date: "05-21", activity: "Tea culture event, support local tea vendors, sustainability talk." },
  { name: "International Day for Biological Diversity", date: "05-22", activity: "Biodiversity survey, nature walk, seed ball making." },
  { name: "World Turtle Day", date: "05-23", activity: "Marine conservation awareness, beach/water body cleanup." },
  { name: "National Brother's Day", date: "05-24", activity: "Community bonding event, sibling appreciation." },
  { name: "Africa Day", date: "05-25", activity: "Cultural diversity celebration, Africa awareness talk." },
  { name: "National Memorial Day", date: "05-26", activity: "Tribute to fallen heroes, wreath laying, patriotic songs." },
  { name: "International Day of Potato", date: "05-30", activity: "Nutrition awareness, community cooking event." },
  { name: "Goa Statehood Day", date: "05-30", activity: "Cultural showcase, Goan heritage celebration." },
  { name: "Hindi Journalism Day", date: "05-30", activity: "Hindi essay competition, journalism workshop." },
  { name: "World No Tobacco Day", date: "05-31", activity: "Anti-tobacco rally, smoking cessation camp, pledge drive." },

  // === JUNE ===
  { name: "World Milk Day", date: "06-01", activity: "Nutrition awareness, milk distribution drive." },
  { name: "Global Day of Parents", date: "06-01", activity: "Parent appreciation event, family wellness session." },
  { name: "Italy Republic Day", date: "06-02", activity: "International culture awareness." },
  { name: "International Sex Workers' Day", date: "06-02", activity: "Social awareness discussion, human rights talk." },
  { name: "Telangana Formation Day", date: "06-02", activity: "State heritage celebration, cultural program." },
  { name: "World Bicycle Day", date: "06-03", activity: "Campus cycling rally, eco-friendly transport awareness." },
  { name: "International Day of Innocent Children Victims of Aggression", date: "06-04", activity: "Child rights awareness, visit children's shelter." },
  { name: "World Environment Day", date: "06-05", activity: "Massive plantation drive, plastic-free campus pledge, clean campus day." },
  { name: "National Donut Day", date: "06-06", activity: "Fun community event, bake sale for charity." },
  { name: "Eid al-Adha", date: "06-07", activity: "Interfaith harmony event, charity and sharing drive." },
  { name: "World Food Safety Day", date: "06-07", activity: "Food hygiene awareness, street food safety campaign." },
  { name: "World Brain Tumour Day", date: "06-08", activity: "Brain health awareness session, neurology camp." },
  { name: "World Oceans Day", date: "06-08", activity: "Ocean conservation awareness, water body cleanup." },
  { name: "National Best Friend Day", date: "06-08", activity: "Buddy volunteering, pair community service." },
  { name: "World Day Against Child Labour", date: "06-12", activity: "Child labour awareness rally, school enrollment drive." },
  { name: "National Red Rose Day", date: "06-12", activity: "Gratitude campaign, thank-you cards for community helpers." },
  { name: "World Blood Donor Day", date: "06-14", activity: "Blood donation camp, donor appreciation, awareness drive." },
  { name: "Flag Day", date: "06-14", activity: "Patriotic rally, flag-making workshop." },
  { name: "World Wind Day", date: "06-15", activity: "Renewable energy awareness, windmill model exhibition." },
  { name: "World Elder Abuse Awareness Day", date: "06-15", activity: "Senior citizen rights talk, old age home visit." },
  { name: "Father's Day", date: "06-15", activity: "Community gratitude event, felicitate father figures." },
  { name: "World Day to Combat Desertification and Drought", date: "06-17", activity: "Water conservation drive, tree planting in dry areas." },
  { name: "Autistic Pride Day", date: "06-18", activity: "Inclusive event, autism acceptance awareness." },
  { name: "International Picnic Day", date: "06-18", activity: "Community outdoor event, nature appreciation." },
  { name: "World Sickle Cell Awareness Day", date: "06-19", activity: "Blood disorder awareness, health camp." },
  { name: "Juneteenth", date: "06-19", activity: "Equality and justice awareness discussion." },
  { name: "World Sauntering Day", date: "06-19", activity: "Mindfulness walk, slow living awareness." },
  { name: "World Refugee Day", date: "06-20", activity: "Refugee awareness talk, donation drive." },
  { name: "World Music Day", date: "06-21", activity: "Musical event for social cause, cultural evening." },
  { name: "World Hydrography Day", date: "06-21", activity: "Water mapping awareness, river conservation." },
  { name: "International Yoga Day", date: "06-21", activity: "Mass yoga session, yoga workshop, wellness camp." },
  { name: "Summer Solstice", date: "06-21", activity: "Sun awareness, solar energy promotion." },
  { name: "World Rainforest Day", date: "06-22", activity: "Forest conservation rally, green campus initiative." },
  { name: "International Olympic Day", date: "06-23", activity: "Sports meet, inter-college tournament for a cause." },
  { name: "United Nations Public Service Day", date: "06-23", activity: "Public service appreciation, governance talk." },
  { name: "International Widow's Day", date: "06-23", activity: "Widow empowerment program, livelihood workshop." },
  { name: "International Day against Drug Abuse and Illicit Trafficking", date: "06-26", activity: "Anti-drug rally, de-addiction awareness camp." },
  { name: "International Day in Support of Victims of Torture", date: "06-26", activity: "Human rights awareness session." },
  { name: "Helen Keller Day", date: "06-27", activity: "Disability awareness event, inclusive activity." },
  { name: "National Statistics Day", date: "06-29", activity: "Data literacy workshop, statistics quiz." },
  { name: "International Day of the Tropics", date: "06-29", activity: "Tropical ecosystem awareness, biodiversity talk." },
  { name: "World Asteroid Day", date: "06-30", activity: "Space science quiz, astronomy awareness event." },

  // === JULY ===
  { name: "National Doctor's Day (India)", date: "07-01", activity: "Felicitate local doctors, free health camp, thank-you cards." },
  { name: "World Zoonoses Day", date: "07-06", activity: "Animal-borne disease awareness, stray animal vaccination drive." },
  { name: "Guru Purnima", date: "07-10", activity: "Teacher appreciation event, guru vandana, campus gratitude program." },
  { name: "World Population Day", date: "07-11", activity: "Population awareness rally, family planning talk." },
  { name: "World Youth Skills Day", date: "07-15", activity: "Skill development workshop, career guidance for youth." },
  { name: "International Nelson Mandela Day", date: "07-18", activity: "67 minutes of community service, social justice awareness." },
  { name: "International Chess Day", date: "07-20", activity: "Chess tournament, strategic thinking workshop." },
  { name: "National Flag Day (India)", date: "07-22", activity: "Flag hoisting ceremony, patriotic event." },
  { name: "Kargil Vijay Diwas", date: "07-26", activity: "Tribute to soldiers, patriotic rally, defence awareness." },
  { name: "Dr. APJ Abdul Kalam Death Anniversary", date: "07-27", activity: "Science quiz, innovation talk, youth motivation session." },
  { name: "World Nature Conservation Day", date: "07-28", activity: "Nature walk, conservation pledge, eco-awareness drive." },
  { name: "World Hepatitis Day", date: "07-28", activity: "Hepatitis awareness camp, free screening coordination." },
  { name: "International Tiger Day", date: "07-29", activity: "Wildlife conservation rally, tiger awareness poster exhibition." },
  { name: "International Friendship Day", date: "07-30", activity: "Buddy volunteering, friendship band making, community bonding." },

  // === AUGUST ===
  { name: "World Lung Cancer Day", date: "08-01", activity: "Anti-smoking rally, lung health awareness camp." },
  { name: "World Wide Web Day", date: "08-01", activity: "Digital literacy workshop, internet safety talk." },
  { name: "Hiroshima Day", date: "08-06", activity: "Peace rally, anti-nuclear awareness, origami cranes." },
  { name: "National Handloom Day", date: "08-07", activity: "Handloom exhibition, support local weavers campaign." },
  { name: "Quit India Movement Day", date: "08-08", activity: "Patriotic rally, freedom struggle quiz, NCC-NSS event." },
  { name: "International Day of the World's Indigenous Peoples", date: "08-09", activity: "Tribal art exhibition, indigenous culture awareness." },
  { name: "Raksha Bandhan", date: "08-09", activity: "Rakhi making for soldiers, community celebration." },
  { name: "World Lion Day", date: "08-10", activity: "Wildlife conservation awareness, Gir forest documentary." },
  { name: "World Biofuel Day", date: "08-10", activity: "Renewable energy workshop, biofuel demo." },
  { name: "International Youth Day", date: "08-12", activity: "Youth empowerment seminar, leadership workshop." },
  { name: "Independence Day (India)", date: "08-15", activity: "Flag hoisting, patriotic rally, cultural program, community service." },
  { name: "World Humanitarian Day", date: "08-19", activity: "Humanitarian service drive, disaster preparedness talk." },
  { name: "Sadbhavna Diwas", date: "08-20", activity: "Communal harmony event, peace pledge, interfaith meeting." },
  { name: "World Mosquito Day", date: "08-20", activity: "Anti-malaria drive, campus cleanliness, fogging awareness." },
  { name: "ISRO Day", date: "08-23", activity: "Space science exhibition, ISRO achievements quiz." },
  { name: "Women's Equality Day", date: "08-26", activity: "Gender equality rally, women empowerment talk." },
  { name: "Mother Teresa Anniversary", date: "08-26", activity: "Community service in her memory, orphanage visit." },
  { name: "National Sports Day", date: "08-29", activity: "Sports event, inter-class games, fitness challenge." },

  // === SEPTEMBER ===
  { name: "National Nutrition Week", date: "09-01", activity: "Nutrition awareness camp, healthy food distribution." },
  { name: "Teachers' Day", date: "09-05", activity: "Teacher appreciation event, gratitude cards, cultural program." },
  { name: "International Day of Charity", date: "09-05", activity: "Charity drive, fundraiser for underprivileged." },
  { name: "International Literacy Day", date: "09-08", activity: "Literacy drive, teach-a-child campaign, book donation." },
  { name: "World Suicide Prevention Day", date: "09-10", activity: "Mental health awareness walk, counseling camp." },
  { name: "National Forest Martyrs Day", date: "09-11", activity: "Tree plantation, forest conservation pledge." },
  { name: "World First Aid Day", date: "09-13", activity: "First-aid training camp, CPR demonstration." },
  { name: "Hindi Diwas", date: "09-14", activity: "Hindi essay competition, poetry recitation." },
  { name: "Engineer's Day", date: "09-15", activity: "Technical quiz, innovation showcase, STEM outreach." },
  { name: "International Day of Democracy", date: "09-15", activity: "Mock parliament, democracy awareness talk." },
  { name: "World Ozone Day", date: "09-16", activity: "Ozone layer awareness rally, eco-friendly product campaign." },
  { name: "World Patient Safety Day", date: "09-17", activity: "Hospital visit, patient care awareness session." },
  { name: "World Bamboo Day", date: "09-18", activity: "Bamboo craft workshop, sustainable living talk." },
  { name: "International Day of Peace", date: "09-21", activity: "Peace walk, white dove release, harmony pledge." },
  { name: "World Alzheimer's Day", date: "09-21", activity: "Senior citizen care visit, Alzheimer's awareness session." },
  { name: "World Rhino Day", date: "09-22", activity: "Wildlife conservation awareness, poster making." },
  { name: "International Day of Sign Languages", date: "09-23", activity: "Sign language workshop, inclusive communication event." },
  { name: "World Pharmacists Day", date: "09-25", activity: "Medicine awareness camp, pharmacist appreciation." },
  { name: "Antyodaya Diwas", date: "09-25", activity: "Service to the last person, village outreach program." },
  { name: "World Contraception Day", date: "09-26", activity: "Reproductive health awareness, youth health talk." },
  { name: "World Environmental Health Day", date: "09-26", activity: "Campus cleanliness drive, environmental health talk." },
  { name: "World Tourism Day", date: "09-27", activity: "Heritage walk, local tourism promotion." },
  { name: "World Rabies Day", date: "09-28", activity: "Anti-rabies awareness, stray dog vaccination drive." },
  { name: "World Rivers Day", date: "09-28", activity: "River cleanup, water conservation rally." },
  { name: "International Day for Universal Access to Information", date: "09-28", activity: "RTI awareness workshop, information literacy talk." },
  { name: "World Heart Day", date: "09-29", activity: "Heart health awareness walk, cardiac check-up camp." },
  { name: "International Translation Day", date: "09-30", activity: "Multilingual event, translation challenge." },

  // === OCTOBER ===
  { name: "Gandhi Jayanti", date: "10-02", activity: "Swachh Bharat drive, cleanliness rally, non-violence pledge." },
  { name: "World Mental Health Day", date: "10-10", activity: "Mental health awareness walk, counseling camp, wellness workshop." },
  { name: "Girl Child Day", date: "10-11", activity: "Girl empowerment rally, education awareness drive." },
  { name: "World Students' Day", date: "10-15", activity: "Student achievements showcase, APJ Kalam tribute, innovation quiz." },
  { name: "World Food Day", date: "10-16", activity: "Food donation drive, zero hunger awareness, community kitchen." },
  { name: "Eradication of Poverty Day", date: "10-17", activity: "Poverty awareness rally, skill development workshop." },
  { name: "National Unity Day", date: "10-31", activity: "Unity rally, Run for Unity, pledge for national integration." },
  { name: "United Nations Day", date: "10-24", activity: "Model UN event, UN awareness talk, global issues discussion." },

  // === NOVEMBER ===
  { name: "World Tsunami Awareness Day", date: "11-05", activity: "Disaster preparedness drill, tsunami awareness session." },
  { name: "National Cancer Awareness Day", date: "11-07", activity: "Cancer screening camp, awareness rally, survivor stories." },
  { name: "World Immunization Day", date: "11-10", activity: "Vaccination drive coordination, immunization awareness." },
  { name: "National Education Day", date: "11-11", activity: "Education awareness rally, free tuition for underprivileged." },
  { name: "Children's Day", date: "11-14", activity: "Visit orphanage, fun activities for children, gift distribution." },
  { name: "Birsa Munda Jayanti", date: "11-15", activity: "Tribal rights awareness, cultural heritage event." },
  { name: "World Toilet Day", date: "11-19", activity: "Sanitation awareness drive, clean toilet campaign." },
  { name: "Universal Children's Day", date: "11-20", activity: "Child rights awareness, school outreach program." },
  { name: "International Day for the Elimination of Violence Against Women", date: "11-25", activity: "Anti-violence rally, self-defence workshop, awareness campaign." },
  { name: "Constitution Day of India", date: "11-26", activity: "Constitution reading, fundamental rights awareness, mock parliament." },

  // === DECEMBER ===
  { name: "World AIDS Day", date: "12-01", activity: "AIDS awareness rally, red ribbon campaign, free testing coordination." },
  { name: "National Pollution Control Day", date: "12-02", activity: "Anti-pollution rally, air quality monitoring, green campus drive." },
  { name: "International Day of Persons with Disabilities", date: "12-03", activity: "Inclusive event, disability rights awareness, assistive tech showcase." },
  { name: "International Volunteer Day", date: "12-05", activity: "Volunteer appreciation, community service marathon, NSS felicitation." },
  { name: "Human Rights Day", date: "12-10", activity: "Human rights awareness rally, debate competition, poster campaign." },
  { name: "Universal Health Coverage Day", date: "12-12", activity: "Free health check-up camp, health insurance awareness." },
  { name: "Vijay Diwas", date: "12-16", activity: "Tribute to soldiers, patriotic rally, defence quiz." },
  { name: "Minorities Rights Day", date: "12-18", activity: "Minority rights awareness, inclusive cultural event." },
  { name: "National Mathematics Day", date: "12-22", activity: "Math quiz, Ramanujan tribute, STEM outreach for school students." },
  { name: "Veer Bal Diwas", date: "12-26", activity: "Bravery stories, youth courage awards, patriotic event." },
];

/** Get events for a specific month-day key like "03-08" */
export function getEventsForDate(date: Date): CalendarEvent[] {
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  const key = `${mm}-${dd}`;
  return calendarEvents.filter((e) => e.date === key);
}

/** Get all dates that have events (for highlighting in calendar) */
export function getEventDatesForMonth(year: number, month: number): Date[] {
  const dates: Date[] = [];
  const seen = new Set<string>();
  for (const ev of calendarEvents) {
    const [mm, dd] = ev.date.split('-').map(Number);
    if (mm === month + 1) {
      const key = `${mm}-${dd}`;
      if (!seen.has(key)) {
        seen.add(key);
        dates.push(new Date(year, month, dd));
      }
    }
  }
  return dates;
}
